endpoint: https://brankas.atlassian.net
password-source: keyring
authentication-method: api-token
user: "Kenneth Shaw"
login: kenneth.shaw@brank.as
custom-commands:
  - name: all-sprint-issues
    help: display all open issues in current sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        {{jira}} list --template table --query "resolution = unresolved and project = $JIRA_PROJECT and sprint in openSprints() order by priority desc, created"
      else
        {{jira}} list --template table --query "resolution = unresolved and sprint in openSprints() order by priority desc, created"
      fi

  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT order by priority desc, created"
      else
        {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() order by priority desc, created"
      fi
