#!/bin/bash

# pushes a supplied file into an environment variable on a dokku host

REMOTE=$(git config remote.dokku.url)

DOKKU=$1
ENVVAR=$2
DFILE=$3

if [ ! -z "$REMOTE" ]; then
  DOKKU=$REMOTE
  ENVVAR=$1
  DFILE=$2
fi

if [[ "$DOKKU" == "" || "$ENVVAR" == "" || "$DFILE" == "" ]]; then
  echo "usage: $(basename $0) <user>@<host>:<app> <envvar> <file>"
  exit 1
fi

set -e

HOST=$(echo "$DOKKU"|awk -F: '{print $1}')
APP=$(echo "$DOKKU"|awk -F: '{print $2}')
DATA=$(base64 -w 0 $DFILE)

if [[ "$HOST" == "" || "$APP" == "" || "$DATA" == "" ]]; then
  echo "unknown error ($HOST -- $APP)"
  exit 1
fi

ssh -t $HOST "config:set $APP $ENVVAR='$DATA'"
